# Classical ML Running, Multiclass Single Label Prediction

In [1]:
# Imports
import numpy as np
import pandas as pd
import time

In [2]:
# generate fake data
from sklearn.datasets import make_classification, make_multilabel_classification
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, f1_score

In [3]:
# for data split
from sklearn.model_selection import train_test_split
from qiskit_algorithms.utils import algorithm_globals
algorithm_globals.random_seed = 123
from pycaret.classification import *

In [ ]:
class classicalAlgoTraining:
    """
    Class to train algorithms."""
    def __init__(self, no_of_features, no_of_samples, no_of_classes, models = ['knn', 'qda', 'rf', 'lightgbm', 'svm']):
        self.no_of_features = no_of_features
        self.no_of_samples = no_of_samples
        # self.no_of_labels = no_of_labels
        self.no_of_classes = no_of_classes
        self.models = models
        print(f"the no of classes is {self.no_of_classes}")

    def data_generation(self):
        """
        Generate classification data using sklearn's data generation.\
        """
        n_samples=self.no_of_samples
        n_features=self.no_of_features
        n_classes=self.no_of_classes
        print(n_samples)
        X, y = make_classification(n_samples=n_samples,
                                   n_features=n_features,
                                   n_classes=n_classes,
                                    n_redundant=0,
                                    n_clusters_per_class=1,
                                    class_sep=2.0,
                                    random_state=algorithm_globals.random_seed
                                    )
        print(f"the number of classses is: {n_classes}")
        return X, y

    # def train_test_split(self):
    #     """
    #     splitting the data into train test split
    #     """
    #     ## Train test split
    #     # X, y = self.data_generation()
    #     train_features, test_features, train_labels, test_labels = train_test_split(
    #         X, y, train_size=0.8, random_state=algorithm_globals.random_seed
    #     )
    #     return train_features, test_features, train_labels, test_labels

    def pycaret_training(self):
        X, y = self.data_generation()
        print(X.shape, y.shape)
        exp_name = setup(data = X,  target = y, train_size=0.8)
        best_model = compare_models(include=self.models, sort='f1')
        # print(best_model)
        results = {}
        for model in self.models:
            model_created = create_model(model, verbose=False)
            model_results = predict_model(model_created)
            short_results = pull(model_created)
            # print(pull(model_created).columns)
            results.setdefault('Model', []).append(short_results['Model'].values[0])
            results.setdefault('Accuracy', []).append(short_results['Accuracy'].values[0])
            results.setdefault('F1', []).append(short_results['F1'].values[0])
            # print(results)
            # pull(model_created).to_csv(f'''results/{model}-features_{self.no_of_features}-samples_{self.no_of_samples}-classes_{self.no_of_classes}.csv''', index=False)
        df = pd.DataFrame(results)
        df.to_csv(f'''results/MC-SL-features_{self.no_of_features}-samples_{self.no_of_samples}-classes_{self.no_of_classes}.csv''', index=False)
        return df

In [257]:
no_of_features = [2, 4, 6, 8, 10]
no_of_samples = [64, 128, 256, 512, 1024, 2048]
no_of_classes = [3, 4, 5]

In [258]:
# 2-feature, 10-samples, 2- class training
for clas in no_of_classes:
    for feature in no_of_features:
        for sample in no_of_samples:
            training_object = classicalAlgoTraining(feature, sample, clas)
            training_object.pycaret_training()

the no of classes is 3
64
the number of classses is: 3
(64, 2) (64,)

the no of classes is 3
128
the number of classses is: 3
(128, 2) (128,)

the no of classes is 3
256
the number of classses is: 3
(256, 2) (256,)

the no of classes is 3
512
the number of classses is: 3
(512, 2) (512,)

the no of classes is 3
1024
the number of classses is: 3
(1024, 2) (1024,)

the no of classes is 3
2048
the number of classses is: 3
(2048, 2) (2048,)

the no of classes is 3
64
the number of classses is: 3
(64, 4) (64,)

the no of classes is 3
128
the number of classses is: 3
(128, 4) (128,)

the no of classes is 3
256
the number of classses is: 3
(256, 4) (256,)

the no of classes is 3
512
the number of classses is: 3
(512, 4) (512,)

the no of classes is 3
1024
the number of classses is: 3
(1024, 4) (1024,)

the no of classes is 3
2048
the number of classses is: 3
(2048, 4) (2048,)

the no of classes is 3
64
the number of classses is: 3
(64, 6) (64,)

the no of classes is 3
128
the number of classses is: 3
(128, 6) (128,)

the no of classes is 3
256
the number of classses is: 3
(256, 6) (256,)

the no of classes is 3
512
the number of classses is: 3
(512, 6) (512,)

the no of classes is 3
1024
the number of classses is: 3
(1024, 6) (1024,)

the no of classes is 3
2048
the number of classses is: 3
(2048, 6) (2048,)

the no of classes is 3
64
the number of classses is: 3
(64, 8) (64,)

the no of classes is 3
128
the number of classses is: 3
(128, 8) (128,)

the no of classes is 3
256
the number of classses is: 3
(256, 8) (256,)

the no of classes is 3
512
the number of classses is: 3
(512, 8) (512,)

the no of classes is 3
1024
the number of classses is: 3
(1024, 8) (1024,)

the no of classes is 3
2048
the number of classses is: 3
(2048, 8) (2048,)

the no of classes is 3
64
the number of classses is: 3
(64, 10) (64,)

the no of classes is 3
128
the number of classses is: 3
(128, 10) (128,)

the no of classes is 3
256
the number of classses is: 3
(256, 10) (256,)

the no of classes is 3
512
the number of classses is: 3
(512, 10) (512,)

the no of classes is 3
1024
the number of classses is: 3
(1024, 10) (1024,)

the no of classes is 3
2048
the number of classses is: 3
(2048, 10) (2048,)

the no of classes is 4
64
the number of classses is: 4
(64, 2) (64,)

the no of classes is 4
128
the number of classses is: 4
(128, 2) (128,)

the no of classes is 4
256
the number of classses is: 4
(256, 2) (256,)

the no of classes is 4
512
the number of classses is: 4
(512, 2) (512,)

the no of classes is 4
1024
the number of classses is: 4
(1024, 2) (1024,)

the no of classes is 4
2048
the number of classses is: 4
(2048, 2) (2048,)

the no of classes is 4
64
the number of classses is: 4
(64, 4) (64,)

the no of classes is 4
128
the number of classses is: 4
(128, 4) (128,)

the no of classes is 4
256
the number of classses is: 4
(256, 4) (256,)

the no of classes is 4
512
the number of classses is: 4
(512, 4) (512,)

the no of classes is 4
1024
the number of classses is: 4
(1024, 4) (1024,)

the no of classes is 4
2048
the number of classses is: 4
(2048, 4) (2048,)

the no of classes is 4
64
the number of classses is: 4
(64, 6) (64,)

the no of classes is 4
128
the number of classses is: 4
(128, 6) (128,)

the no of classes is 4
256
the number of classses is: 4
(256, 6) (256,)

the no of classes is 4
512
the number of classses is: 4
(512, 6) (512,)

the no of classes is 4
1024
the number of classses is: 4
(1024, 6) (1024,)

the no of classes is 4
2048
the number of classses is: 4
(2048, 6) (2048,)

the no of classes is 4
64
the number of classses is: 4
(64, 8) (64,)

the no of classes is 4
128
the number of classses is: 4
(128, 8) (128,)

the no of classes is 4
256
the number of classses is: 4
(256, 8) (256,)

the no of classes is 4
512
the number of classses is: 4
(512, 8) (512,)

the no of classes is 4
1024
the number of classses is: 4
(1024, 8) (1024,)

the no of classes is 4
2048
the number of classses is: 4
(2048, 8) (2048,)

the no of classes is 4
64
the number of classses is: 4
(64, 10) (64,)

the no of classes is 4
128
the number of classses is: 4
(128, 10) (128,)

the no of classes is 4
256
the number of classses is: 4
(256, 10) (256,)

the no of classes is 4
512
the number of classses is: 4
(512, 10) (512,)

the no of classes is 4
1024
the number of classses is: 4
(1024, 10) (1024,)

the no of classes is 4
2048
the number of classses is: 4
(2048, 10) (2048,)

the no of classes is 5
64

ValueError: n_classes(5) * n_clusters_per_class(1) must be smaller or equal 2**n_informative(2)=4

In [ ]:
results = training_object.pycaret_training()

In [229]:
results

                             Model  Accuracy   F1
0           K Neighbors Classifier       1.0  1.0
1  Quadratic Discriminant Analysis       1.0  1.0
2         Random Forest Classifier       1.0  1.0
3  Light Gradient Boosting Machine       1.0  1.0
4              SVM - Linear Kernel       1.0  1.0

In [4]:
results = {}

In [5]:
class classicalMultiLabelAlgoTraining:
    """
    Class to train algorithms."""
    def __init__(self, no_of_features, no_of_samples, no_of_classes, no_of_labels, models = ['knn', 'qda', 'rf', 'lightgbm', 'svm']):
        self.no_of_features = no_of_features
        self.no_of_samples = no_of_samples
        self.no_of_labels = no_of_labels
        self.no_of_classes = no_of_classes
        self.models = models
        print(f"the no of classes is {self.no_of_classes}")

    def data_generation(self):
        """
        Generate classification data using sklearn's data generation.\
        """
        n_samples=self.no_of_samples
        n_features=self.no_of_features
        n_classes=self.no_of_classes
        n_labels=self.no_of_labels
        print(n_samples)
        X, y = make_multilabel_classification(n_samples=n_samples, 
                                              n_features=n_features, 
                                              n_classes=n_classes, 
                                              n_labels=n_labels,
                                              random_state=algorithm_globals.random_seed
                                             )
        y_new = np.array([self.conv_to_int(val) for val in y])
        # y_new = y[:,0]*(2**4)+y[:,1]*(2**3)+y[:,2]*(2**2)+y[:,3]*(2**1)+y[:,4]*(2**0)
        # y_new = y[:,0]*(2**2)+y[:,1]*(2**1)+y[:,2]*(2**0)
        # y_new = y[:,0]*(2**1)+y[:,1]*(2**0)
        print(X.shape, y.shape, y_new.shape)
        print(X[:5], y[:5], y_new[:5])
        return X, y, y_new

    def int_to_hot(self, x):
        format = '{' + '0:0{:d}b'.format(self.no_of_classes) + '}'
        result = format.format(x)
        list_of_ints = [int(x) for x in result]
        return np.array(list_of_ints)

    def get_mapping(self):
        dictionary = {}
        numbers = list(range(0, 2**self.no_of_classes))
        for i in numbers:
            dictionary[i] = self.int_to_hot(i)
        return dictionary

    def conv_to_int(self, vector):
        val = "".join(vector.astype(str))
        value = int(val, 2)
        return value
        
    def get_mapping_old(self):
        mapping = {0: [0, 0, 0, 0, 0], 1: [0, 0, 0, 0, 1], 2: [0, 0, 0, 1, 0], 3: [0, 0, 0, 1, 1], 4: [0, 0, 1, 0, 0], 5: [0, 0, 1, 0, 1], 6: [0, 0, 1, 1, 0], 7: [0, 0, 1, 1, 1], 8: [0, 1, 0, 0, 0], 9: [0, 1, 0, 0, 1], 10: [0, 1, 0, 1, 0], 11: [0, 1, 0, 1, 1], 12: [0, 1, 1, 0, 0], 13: [0, 1, 1, 0, 1], 14: [0, 1, 1, 1, 0], 15: [0, 1, 1, 1, 1], 16: [1, 0, 0, 0, 0], 17: [1, 0, 0, 0, 1], 18: [1, 0, 0, 1, 0], 19: [1, 0, 0, 1, 1], 20: [1, 0, 1, 0, 0], 21: [1, 0, 1, 0, 1], 22: [1, 0, 1, 1, 0], 23: [1, 0, 1, 1, 1], 24: [1, 1, 0, 0, 0], 25: [1, 1, 0, 0, 1], 26: [1, 1, 0, 1, 0], 27: [1, 1, 0, 1, 1], 28: [1, 1, 1, 0, 0], 29: [1, 1, 1, 0, 1], 30: [1, 1, 1, 1, 0], 31: [1, 1, 1, 1, 1]}
        return mapping
        # mapping = {0: [0,0,0], 1: [0,0,1], 2:[0,1,0], 3:[0,1,1], 4:[1, 0, 0], 5:[1, 0, 1], 6:[1, 1, 0], 7:[1, 1, 1]}
        # mapping = {0: [0,0], 1: [0,1], 2: [1,0], 3:[1,1]}
        

    # def train_test_split(self):
    #     """
    #     splitting the data into train test split
    #     """
    #     ## Train test split
    #     # X, y = self.data_generation()
    #     train_features, test_features, train_labels, test_labels = train_test_split(
    #         X, y, train_size=0.8, random_state=algorithm_globals.random_seed
    #     )
    #     return train_features, test_features, train_labels, test_labels

    def pycaret_training(self):
        X, y, y_new = self.data_generation()
        print(X.shape, y.shape, y_new.shape)
        exp_name = setup(data = X,  target = y_new.reshape(-1), train_size=0.8)
        # best_model = compare_models(include=self.models, sort='f1')
        # print(best_model)
        # results = {}
        mapping = self.get_mapping()
        for model in self.models:
            start = time.time()
            model_created = create_model(model, verbose=False)
            end = time.time()
            time_elapsed = end - start
            predicted_model = predict_model(model_created)
            predictions = model_created.predict(X)
            short_results = pull(model_created)
            # print(pull(model_created).columns)
            # Define the mapping
            

            # Use list comprehension to create the new array
            predictions_labels_final = np.array([mapping[val] for val in predictions])
            print(predictions_labels_final[:5])
            accuracy_scores = accuracy_score(y, predictions_labels_final)
            f1_scores = f1_score(y, predictions_labels_final, average='weighted')
            results.setdefault('Model', []).append(short_results['Model'].values[0])
            results.setdefault('No of features', []).append(self.no_of_features)
            results.setdefault('No of samples', []).append(self.no_of_samples)
            results.setdefault('No of classes', []).append(self.no_of_classes)
            results.setdefault('No of labels', []).append(self.no_of_labels)
            
            results.setdefault('Accuracy', []).append(accuracy_scores)
            results.setdefault('F1', []).append(f1_scores)
            results.setdefault('Time taken', []).append(time_elapsed)
            # results.setdefault('F1 Score from model', []).append(short_results['F1'].values[0])
        # df = pd.DataFrame(results)
        # df.to_csv(f'''results/MC-ML-features_{self.no_of_features}-samples_{self.no_of_samples}-classes_{self.no_of_classes}-labels_{self.no_of_labels}.csv''', index=False)
        # return df

In [9]:
results = {}
no_of_features = [12,16,32,48,64] # as much as quantum side allows
no_of_samples = 1024 # only 1024
no_of_classes = [3] # look for quantum side
no_of_labels = [3] # starting from 2, till max no of classes.

In [10]:
for no_feature in no_of_features:
    for no_class in no_of_classes:
        for no_label in no_of_labels:
            if no_label <= no_class:
                # print(f"the setup is {no_feature}, {no_class}, {no_label}")
                training_object = classicalMultiLabelAlgoTraining(no_feature, no_of_samples, no_class, no_label)
                training_object.pycaret_training()

the no of classes is 3
1024
(1024, 12) (1024, 3) (1024,)
[[ 2.  5.  2.  4.  4.  1. 11.  6.  2.  0.  5.  2.]
 [ 3.  4.  3.  3.  3.  2.  8.  1.  1.  1.  4.  6.]
 [ 8.  5.  2.  0.  1.  5.  7.  4.  5.  6.  6.  5.]
 [ 5.  4.  6.  3.  2.  6.  2.  1.  1.  3.  1.  9.]
 [ 7.  6.  2.  0.  3.  3.  8.  4.  0.  1.  5.  6.]] [[1 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]] [5 6 3 5 6]
(1024, 12) (1024, 3) (1024,)

[[1 0 1]
 [1 1 1]
 [0 1 0]
 [0 0 1]
 [1 1 0]]

[[1 0 0]
 [1 0 0]
 [0 1 1]
 [0 1 1]
 [1 1 0]]

[[1 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]

[[1 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]

[[1 0 0]
 [1 0 1]
 [0 1 0]
 [1 1 1]
 [1 1 0]]
the no of classes is 3
1024
(1024, 16) (1024, 3) (1024,)
[[2. 7. 0. 1. 3. 6. 3. 2. 2. 2. 3. 6. 0. 3. 2. 1.]
 [2. 1. 1. 4. 2. 3. 2. 4. 3. 4. 4. 6. 2. 1. 4. 0.]
 [2. 6. 1. 3. 3. 5. 8. 5. 2. 2. 2. 0. 4. 2. 2. 1.]
 [2. 6. 3. 1. 1. 8. 3. 4. 4. 3. 2. 3. 2. 2. 1. 1.]
 [2. 5. 1. 2. 4. 5. 6. 3. 1. 2. 3. 5. 1. 4. 3. 4.]] [[1 1 0]
 [0 0 0]
 [1 0 0]
 [1 1 1]
 [1 0 1]] [6 0 4 7 5]
(1024, 16) (1024, 3) (1024,)

[[1 1 1]
 [0 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]]

[[1 1 1]
 [0 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]]

[[1 1 1]
 [0 0 0]
 [1 0 0]
 [1 1 1]
 [1 0 1]]

[[1 1 0]
 [0 0 0]
 [1 0 0]
 [1 1 1]
 [1 0 1]]

[[1 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
the no of classes is 3
1024
(1024, 32) (1024, 3) (1024,)
[[1. 1. 2. 1. 0. 3. 2. 1. 0. 3. 2. 2. 2. 1. 3. 0. 2. 2. 4. 0. 2. 1. 1. 3.
  1. 1. 2. 1. 1. 3. 2. 1.]
 [3. 3. 5. 2. 2. 1. 3. 2. 0. 0. 2. 0. 2. 4. 3. 1. 2. 2. 4. 1. 3. 0. 2. 2.
  1. 2. 3. 2. 0. 4. 0. 2.]
 [4. 2. 1. 1. 0. 1. 3. 2. 2. 2. 0. 4. 0. 1. 1. 0. 2. 0. 1. 2. 1. 0. 1. 0.
  1. 2. 0. 1. 1. 0. 2. 1.]
 [2. 0. 1. 2. 0. 0. 2. 7. 1. 2. 2. 0. 1. 2. 1. 4. 1. 1. 2. 3. 4. 1. 0. 2.
  2. 0. 4. 2. 1. 2. 3. 0.]
 [1. 5. 0. 3. 2. 2. 2. 0. 0. 0. 0. 2. 2. 0. 2. 3. 1. 4. 4. 3. 2. 0. 1. 4.
  3. 1. 0. 1. 0. 0. 2. 0.]] [[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]] [7 7 7 0 6]
(1024, 32) (1024, 3) (1024,)

[[1 1 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]]

[[1 1 1]
 [1 1 1]
 [0 0 1]
 [0 0 0]
 [1 1 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 0]]

[[1 1 0]
 [1 1 0]
 [1 1 1]
 [1 1 0]
 [1 1 0]]
the no of classes is 3
1024
(1024, 48) (1024, 3) (1024,)
[[0. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 2. 1. 2. 2. 1. 1. 0. 2. 0. 4.
  1. 3. 0. 1. 3. 0. 0. 0. 1. 1. 1. 3. 1. 1. 1. 2. 3. 1. 0. 0. 2. 1. 2. 0.]
 [0. 2. 0. 0. 1. 0. 4. 1. 0. 0. 2. 1. 0. 1. 0. 2. 5. 0. 3. 0. 1. 1. 0. 1.
  3. 1. 4. 1. 1. 4. 0. 1. 2. 0. 1. 0. 0. 1. 0. 0. 2. 2. 0. 0. 1. 0. 0. 1.]
 [1. 1. 2. 2. 0. 0. 1. 1. 0. 0. 0. 1. 0. 3. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1.
  0. 0. 2. 1. 0. 0. 2. 2. 1. 0. 2. 0. 0. 2. 1. 0. 3. 0. 2. 1. 0. 0. 2. 3.]
 [0. 1. 1. 3. 0. 4. 2. 0. 2. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 6. 2. 1. 3. 0.
  4. 1. 3. 3. 1. 0. 3. 0. 1. 0. 0. 4. 2. 1. 0. 0. 1. 1. 0. 2. 0. 0. 0. 1.]
 [1. 1. 2. 0. 2. 0. 2. 1. 0. 0. 0. 0. 0. 0. 2. 0. 1. 0. 2. 0. 1. 0. 4. 2.
  0. 1. 0. 2. 1. 1. 0. 1. 2. 0. 0. 1. 1. 1. 1. 2. 2. 1. 1. 0. 2. 1. 0. 0.]] [[0 0 0]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]] [0 2 7 7 7]
(1024, 48) (1024, 3) (1024,)

[[0 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

[[0 0 0]
 [1 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 1]]

[[0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

[[0 0 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

[[0 0 0]
 [1 1 0]
 [0 0 1]
 [1 1 1]
 [1 1 1]]
the no of classes is 3
1024
(1024, 64) (1024, 3) (1024,)
[[1. 0. 3. 0. 0. 1. 3. 1. 0. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 1. 2. 0. 0. 1.
  1. 0. 1. 2. 0. 2. 2. 1. 1. 0. 2. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0.
  1. 4. 0. 1. 0. 0. 0. 1. 2. 0. 0. 0. 0. 1. 0. 4.]
 [2. 3. 1. 0. 0. 1. 2. 1. 1. 1. 0. 0. 0. 0. 3. 0. 0. 1. 3. 0. 0. 0. 4. 0.
  0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 2. 0. 2. 0. 2. 1. 0. 0. 0. 2. 1. 0.
  0. 0. 0. 1. 0. 0. 2. 3. 1. 0. 0. 1. 2. 1. 0. 0.]
 [1. 0. 1. 0. 0. 0. 1. 3. 1. 1. 2. 0. 0. 0. 0. 1. 1. 0. 1. 1. 3. 0. 0. 1.
  3. 1. 0. 0. 0. 2. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 3.
  0. 1. 1. 3. 2. 1. 0. 2. 1. 0. 0. 2. 2. 0. 2. 0.]
 [1. 3. 0. 0. 1. 0. 0. 0. 0. 0. 0. 2. 4. 0. 2. 0. 3. 0. 0. 3. 2. 1. 0. 0.
  1. 0. 2. 4. 0. 0. 0. 1. 0. 0. 2. 1. 0. 0. 0. 1. 3. 1. 1. 0. 0. 2. 0. 0.
  0. 2. 1. 0. 2. 0. 1. 0. 0. 2. 0. 1. 2. 0. 0. 0.]
 [1. 3. 1. 0. 0. 1. 3. 0. 1. 0. 0. 2. 0. 0. 1. 2. 1. 3. 1. 0. 0. 0. 1. 2.
  0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 2. 1. 0. 0. 2. 0. 0.
  1. 1. 0. 0. 0. 1. 2. 1. 0. 0. 2. 0. 2. 0. 0. 1.]] [[0 1 0]
 [1 0 1]
 [0 0 0]
 [1 0 0]
 [1 1 1]] [2 5 0 4 7]
(1024, 64) (1024, 3) (1024,)

[[0 1 0]
 [1 0 1]
 [0 0 0]
 [1 1 1]
 [1 1 0]]

[[0 1 0]
 [1 0 1]
 [0 0 0]
 [1 1 0]
 [1 1 0]]

[[0 1 0]
 [1 0 1]
 [0 0 0]
 [1 1 0]
 [1 1 1]]

[[0 1 0]
 [1 0 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]]

[[0 1 0]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [1 1 0]]

In [11]:
df = pd.DataFrame(results)
df.to_csv(f'''results/Final/for-writing/MC-ML-experiments.csv''', index=False)